name: Build application

on: 
    pull_request: 
        branches: 
            - main
    push:
        branches:
            - main
    workflow_dispatch: 

concurrency:
  group: PocketSparks-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Copy CI gradle.properties
              run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
            
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: 11
                distribution: 'zulu'
            
            - name: Generate cache key
              run: ./scripts/checksum.sh ./ checksum.txt

            - uses: actions/cache@v4
              with:
                path: |
                  ~/.gradle/caches/modules-*
                  ~/.gradle/caches/jars-*
                  ~/.gradle/caches/build-cache-*
                key: gradle-${{ hashFiles('checksum.txt') }}

            - name: Check formatting
              working-directory: ./
              run: ./gradlew --init-script buildscripts/init.gradle.kts spotlessCheck --stacktrace

            - name: Build debug
              working-directory: ./
              run: ./gradlew assembleDebug --stacktrace
            - name: Enable KVM group perms
              run: |
                  echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
                  sudo udevadm control --reload-rules
                  sudo udevadm trigger --name-match=kvm
            - name: Run local tests
              working-directory: ./
              run: ./gradlew testDebug --stacktrace
      
            - name: Upload build outputs (APKs)
              uses: actions/upload-artifact@v4
              with:
                name: build-outputs
                path: ./app/build/outputs
      
            - name: Upload build reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: build-reports
                path: ./app/build/reports